# docker-compose.yml
version: '3'
services:
  db:
    build: .
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: dev
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
